### ISSUE TITLE
Misleading error when keyspace ain't found (Cannot achieve consistency level QUORUM)

### ISSUE THREAD

**Issue by ms-xy** [HolmesProcessing/Holmes-Storage#62]
Maybe this only applies to the old version I'm currently still working on. Can't test it right now on the current version, I'll be able to do that on Monday maybe.

The error pops up, when you specify the wrong keyspace in the config file (lets say "holmes" but you set up your keyspace as "holmes_totem").
Storage reports "cannot achieve consistency level QUORUM", which is totally misleading. It should be a "keyspace does not exist" or something. But most definitly not the error I'm getting.
Now as I've said, that might only apply to my old version - I'm not entirely sure what was added / changed since I last merged with upstream. (Didn't see any commits related to this or that could be relevant, but that doesn't mean that there ain't any)

**Comment by Ma-Shell** [comment]
The old version creates the keyspace, if it does not exist. It does so, with "replication = {'class': 'NetworkTopologyStrategy', 'dc1': '2'};". This is why you are getting that misleading error (I'm not trying to defend that behaviour, just explaining why you are getting this error).
I haven't tested with v2, but from skimming through the code, I don't think, v2 automatically creates the keyspace for you, so you should get a better error in v2.

**Comment by cynexit** [comment]
I get the error
`Keyspace thisisatest does not exist`
instead of the one you're seeing. Please make sure

- you build everything with the newest gocql version
- that your C* cluster can actually achieve QUORUM (try a simple select using cqlsh WITH the same QUORUM level storage is using)
- that the keyspace you provided is not existing on _any_ node by accident

I will reopen this issue as soon as someone can confirm and reproduce it.
